### ISSUE TITLE
first two logs largely overlap, with 7 hours difference in timestamps

### ISSUE THREAD

**Issue by tromp** [Grinnode-live/GRIN-papyrus#3]
I'd prefer to see logs from a single timezone, with no duplication of messages.
You could use the short section from my earlier issue, and change the timestamps by 7 hours?!

**Comment by MCM-Mike** [comment]
I could copy&paste the logs from https://freenode.irclog.whitequark.org/bitcoin-wizards/ 
using the following links, which should be same time zone (UTC):

- https://freenode.irclog.whitequark.org/bitcoin-wizards/2016-08-01
- https://freenode.irclog.whitequark.org/bitcoin-wizards/2016-08-02
- https://freenode.irclog.whitequark.org/bitcoin-wizards/2016-08-03

and change the log files accordingly:

- https://github.com/MCM-Mike/GRIN-papyrus/blob/master/2016-08-01.log
- https://github.com/MCM-Mike/GRIN-papyrus/blob/master/2016-08-02.log
- https://github.com/MCM-Mike/GRIN-papyrus/blob/master/2016-08-03.log

Would you agree @tromp ?

**Comment by tromp** [comment]
If you use logs from freenode.irclog.whitequark.org, then you don't need one for 2016-08-01, as the initial announcement in their timezone is on 2016-08-02.

So that would indeed be the simplest solution.
You can also add https://freenode.irclog.whitequark.org/bitcoin-wizards/2016-08-04 which contains further mention of mimblewimble (which 2016-08-05 no longer does).

**Comment by MCM-Mike** [comment]
> If you use logs from freenode.irclog.whitequark.org, then you don't need one for 2016-08-01, as the initial announcement in their timezone is on 2016-08-02.
> 
> So that would indeed be the simplest solution.
> You can also add https://freenode.irclog.whitequark.org/bitcoin-wizards/2016-08-04 which contains further mention of mimblewimble (which 2016-08-05 no longer does).

ok, I will add:

https://freenode.irclog.whitequark.org/bitcoin-wizards/2016-08-02
https://freenode.irclog.whitequark.org/bitcoin-wizards/2016-08-03
https://freenode.irclog.whitequark.org/bitcoin-wizards/2016-08-04

and remove the 
https://github.com/MCM-Mike/GRIN-papyrus/blob/master/2016-08-01.log

**Comment by tromp** [comment]
Thanks, Mike!

**Comment by MCM-Mike** [comment]
made all changes and additionally I tried to add a summary of the first appearance of the tor link on IRC:
https://github.com/MCM-Mike/GRIN-papyrus/blob/master/mimblewimble-document-first-public-appearance.md
